### ISSUE TITLE
feat: don't strip orientation EXIF data

### ISSUE THREAD

**Issue by NecroHamster987** [revoltchat/autumn#20]
![Screenshot_20220216-112116_Chrome Beta](https://user-images.githubusercontent.com/99824724/154311514-3e71ad9a-cb60-4cb3-98eb-0dc709a42d42.jpg)

Images rotate upon being posted so that they are sideways, or upside down when the image is from the phone's camera roll. If the image is a screenshot however rotation does not happen.

**Comment by janderedev** [comment]
Currently working on this
