### ISSUE TITLE
bug: Incorrect image dimensions for JPEG.

### ISSUE THREAD

**Issue by itzTheMeow** [revoltchat/autumn#32]
### What happened?

Image: https://autumn.revolt.chat/attachments/hJbF5z9JZXthhuVgXa6SUYK7RBrvVtxfn5xbA1k0EJ
Attachment:
```json
{
  "_id": "hJbF5z9JZXthhuVgXa6SUYK7RBrvVtxfn5xbA1k0EJ",
  "tag": "attachments",
  "filename": "IMG_2567.jpeg",
  "metadata": {
    "type": "Image",
    "width": 4032,
    "height": 3024
  },
  "content_type": "image/jpeg",
  "size": 1532809
}
```

The actual image is 3024x4032, but the attachment metadata on the message shows it being 4032x3024. (is this related to #21?) The image was taken on an iPhone 12.

**Comment by insertish** [comment]
There was a PR that fixed this a while back.
