### ISSUE TITLE
issue: "cannot assign requested address and namespace" with MongoDB and credentials

### ISSUE THREAD

**Issue by toastxc** [revoltchat/autumn#33]
### What do you want to see?

My current understand is that Autumn does not currently support using a password or username in production.

I used the following redacted URI for Mongo, I believe this should work but recieved an error
`AUTUMN_MONGO_URI="mongodb://username:password@localhost:27017/database"`
`cannot assign requested address and namespace (error 99)`

While database authentication is certainly not needed, I'd appreciate its implementation

**Comment by insertish** [comment]
It certainly does support it because we use both authentication and TLS in production, this seems to be an unrelated bug.

**Comment by insertish** [comment]
This issue is stale, if a reproduction of the issue does show up, please post and re-open.
We are using username:password connection strings in production with no issue.
