### ISSUE TITLE
feat: JPEG-XL, AVIF support

### ISSUE THREAD

**Issue by insertish** [revoltchat/autumn#5]

**Comment by janderedev** [comment]
WebP should be supported already? Might be a Revite issue
![image](https://user-images.githubusercontent.com/26145882/167493861-1918ebc0-05eb-4862-bdb7-f90610d815c8.png)

**Comment by janderedev** [comment]
^ To add to the missing filetypes, .mkv, .wav and .ogg should also be added

**Comment by insertish** [comment]
Superseded by https://github.com/revoltchat/backend/issues/342 and https://github.com/revoltchat/backend/issues/343
